# Netlify settings. These override the settings in the UI.
[build]
  base    = ""
  command = "make www"
  publish = "www"

[[headers]]
  for = "/*"
  [headers.values]
    Website-Version = "01"

# Note that `/index.html` and `/` are not the same in Netlify even though
# index.html gets served at both locations.
[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"

[[redirects]]
  from = "http://bash-template.com"
  to = "https://bash-template.com"
  status = 200
