# Netlify settings. These override the settings in the UI.
[build]
  base    = ""
  command = "make www"
  publish = "www"

[[headers]]
  for = "/*"
  [headers.values]
    Website-Version = "01"

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/plain; charset=ascii"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/plain; charset=ascii"
