name: tests

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  schedule:
    - cron:  '11 */3 * * *'

jobs:
  tests-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:

    - name: checkout repository
      uses: actions/checkout@master

    - name: create symlink
      run: ln -s $(pwd) ~/bash-template

    - name: install APT packages
      run: |
        sudo apt-get install curl
        sudo apt-get install httpie

    - name: test website contents
      shell: bash {0}
      run: ~/bash-template/tests/test-website.sh

    - name: test shell scripts with shellcheck
      shell: bash {0}
      run: ~/bash-template/tests/test-shell-scripts-with-shellcheck.sh

    - name: test template.sh exit codes
      shell: bash {0}
      run: ~/bash-template/tests/test-template-exit-codes.sh

    - name: Install and configure awscli
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        sudo pip install awscli
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile bash-template-read-only
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile bash-template-read-only
        aws iam list-users --profile bash-template-read-only

    - name: Install terraform, configure it, then check for pending changes (fail if there are any)
      env:
        TERRAFORM_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
        BUDGET_ALERTS_EMAIL: ${{ secrets.BUDGET_ALERTS_EMAIL }}
      run: |
        cd /tmp
        wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        unzip terraform_0.12.24_linux_amd64.zip
        echo -e "credentials \"app.terraform.io\" {\n  token = \"${TERRAFORM_TOKEN}\"\n}" > /tmp/terraformrc
        cd ~/bash-template/terraform
        mkdir .terraform
        echo "prod" > .terraform/environment
        TF_CLI_CONFIG_FILE=/tmp/terraformrc /tmp/terraform init
        TF_CLI_CONFIG_FILE=/tmp/terraformrc /tmp/terraform plan -var="budget_alerts_email=${BUDGET_ALERTS_EMAIL}" -var="aws_profile=bash-template-read-only" -detailed-exitcode
