name: tests

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  schedule:
    - cron:  '11 8 * * *'

jobs:
  tests-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:

    - name: checkout repository
      uses: actions/checkout@master

    - name: create symlink
      run: ln -s $(pwd) ~/bash-template

    - name: install APT packages
      run: |
        sudo apt-get install curl
        sudo apt-get install httpie

    - name: test website contents
      shell: bash {0}
      run: ~/bash-template/tests/test-website.sh
